#pragma once

#define BATTERY_LOW 30
#define BATTERY_VERY_LOW 20
#define BATTERY_FULL_CAPACITY 4200
#define BATTERY_LOW_CAPACITY 3300

#define CPU_FREQUENCY 40

#define DISPLAY_ADJUST 240

#define TICK_SLEEP 200
#define TICK_WAKEUP 10
