#pragma once

#include <Arduino.h>

#define LILYGO_WATCH_2020_V3

#define APP_FULL_NAME "CyberWatch 1.0"
#define APP_NAME "CyberWatch"
#define APP_VERSION "1.0"

#define BATTERY_LOW 30
#define BATTERY_VERY_LOW 20
#define BATTERY_FULL_CAPACITY 4200
#define BATTERY_LOW_CAPACITY 3200

#define CPU_FREQUENCY_LOW 20
#define CPU_FREQUENCY_HIGH 240
#define CROSS_SWIPE_TOLERANCE 12

#define COLOR_BACKGROUND 0x0000

#define COLOR_MAIN_1 0x07E0
#define COLOR_MAIN_2 0x001F
#define COLOR_MAIN_3 0x03EF

#define COLOR_WARN 0xF800

#define DISPLAY_ADJUST 80

#define SERIAL_RATE 19200

#define SLEEPCYCLE_MS 100
#define TICK_WAKEUP 10

#define TICKER_BATTERY 1200
#define TICKER_DATETIME 2
#define TICKER_CLOCKS 80
#define TICKER_STEPS 20
#define TICKER_DETECT_ONHAND 5

#define DETECT_ONHAND_ACC_THRESHOLD 50

#define INACTIVITY_ONHAMD_TRESHOLD 5
#define INACTIVITY_TRESHOLD 5